### ISSUE TITLE
Distribute a pre-compiled version for Windows

### ISSUE THREAD

**Issue by XaviscoB** [sakertooth/spiff#1]
I'm trying to compile it myself, but I'm getting an error every time I try to start the compilation using Make. Would it be possible to compile it and make it available for Windows?

Error => 

![image](https://github.com/sakertooth/spiff/assets/130815183/9a219b96-b63d-4358-9761-b07effea3ced)

**Comment by sakertooth** [comment]
> Would it be possible to compile it and make it available for Windows?

If you have MSVC, CMake should automatically use MSVC under the hood. Though, the errors you shown are linker errors, so perhaps you did not have all the libraries installed?

Also wanted to mention that Spiff was a experimental project for me to learn a bit more with CMake and the Minecraft protocol, so I haven't done much to update it. I don't recall if there were any actual issues with the project itself since I haven't worked on it for so long.

**Comment by XaviscoB** [comment]
> > Would it be possible to compile it and make it available for Windows?
> 
> If you have MSVC, CMake should automatically use MSVC under the hood. Though, the errors you shown are linker errors, so perhaps you did not have all the libraries installed?
> 
> Also wanted to mention that Spiff was a experimental project for me to learn a bit more with CMake and the Minecraft protocol, so I haven't done much to update it. I don't recall if there were any actual issues with the project itself since I haven't worked on it for so long.

I can't say for sure, I don't have much experience with CMake or C++. The only thing I did was clone the repository and the repositories of the required libraries.

Main Folder =>
![image](https://github.com/sakertooth/spiff/assets/130815183/00fd1b5a-b5a2-49ad-b927-5ff4a3b95ac3)

Asio Folder => 
![image](https://github.com/sakertooth/spiff/assets/130815183/be2a6248-70ff-45c8-b08d-ca72eaa64eb7)

BotCraft Folder =>
![image](https://github.com/sakertooth/spiff/assets/130815183/69927a84-53f5-413c-a273-8e840b3b0e86)

**Comment by sakertooth** [comment]
I think you should try explicitly linking to winsock when compiling. Try configuring cmake with `cmake ..-DCMAKE_CXX_FLAGS=-lws2_32`

**Comment by sakertooth** [comment]
I committed a change that links to winsock for Windows, and assuming you have the Windows SDK installed, the build should work.

Closing.

**Comment by sakertooth** [comment]
Hey @XaviscoB, I no longer have much interest in further development on Spiff, so I archived this repository. However, I wanted to confirm if the change I committed actually fixed your issue and the problem was really resolved. I don't have a Windows machine to test this with and I don't have a cross compiling tool chain setup to cross compile for Windows at the moment.
